name: uuid_enhanced
version: 3.0.2
description: >
  RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
authors:
  - Yulian Kuncheff <yulian@kuncheff.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/truongsinh/dart-uuid
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.1
dev_dependencies:
  # perfectionist:
  #   git:
  #     url: https://github.com/marciovalim/perfectionist.git
  #     ref: master
  test: ^1.17.10
